### ISSUE TITLE
Technical research

### ISSUE THREAD

**Issue by dinhnhat0401** [BlockchainDevTokyo/referral_link#1]
Problems:
-  Connect vào testnet của near
- Tạo ra ví để trả thưởng A: 100 near
- Tìm cách: Connect ví của người dùng

Link:
https://www.ref.finance/
https://pancakeswap.finance/pools

**Comment by v3kthp** [comment]
Các tool của near:
- JavaScript SDK: Kết nối, đăng ký, giao dịch và triển khai với bất kỳ mạng lưới NEAR nào từ bất kỳ JS context nào.
- Rust Contract SDK: Xây dựng các hợp đồng an toàn, bảo mật để quản lý các tài sản có giá trị cao.
- AssemblyScript Contract SDK: Tìm hiểu và tạo nguyên bản bằng cú pháp JS.
- JSON RPC API: Tất cả các thông tin giao tiếp với nền tảng đều thông qua API này.
- Near CLI: cung cấp tập hợp những câu lệnh cho phép người dùng tương tác với hệ thống blockchain của Near (ví dụ: tạo account, kiểm tra trạng thái của một giao dịch etc…)
- NEAR Explorer: Near Explorer: hiển thị trực quan theo thời gian thực các thông tin liên quan đến Near blockchain, cho phép kiểm tra thông tin các tài khoản Near, lịch sử giao dịch etc..
- Near Wallet: Ứng dụng web cho phép tạo và tương tác với những tài khoản người dùng của Near. Giao diện ứng dụng thân thiện và dễ dàng sử dụng trên các thiết bị mobile hoặc máy tính
- NEARUP: Quản lý triển khai cục bộ và tham gia bất kỳ mạng lưới công cộng hoặc riêng tư nào.
- Bridge: Khả năng tương tác nhanh, an toàn.
- EVM: Máy ảo tương thích với Ethereum.

**Comment by v3kthp** [comment]
Tạo ví testnet trên https://wallet.testnet.near.org/
Trong ví có sẵn 200 near

**Comment by v3kthp** [comment]
run sample use near-api-js
https://docs.near.org/vi/docs/api/naj-quick-reference
Đang bị lỗi khi chạy nodejs :(
"Error: Cannot find module 'near-api-js'"

**Comment by v3kthp** [comment]
Đã connect thành công tới ví và lấy được accountId và balance

  const near = await nearAPI.connect({ keyStore, ...nearConfig }); -> tạo kết nối tới near service

const walletConnection = new nearAPI.WalletConnection(near); -> tạo kết nối tới ví near

walletConnection.getAccountId() -> accountId của near, dùng thay thế cho public key

utils.format.formatNearAmount((await (await walletConnection.account()).getAccountBalance()).total) -> lấy total  của balance của ví
Ngoài total ra thì còn có thể lấy được 1 vài thông tin khác từ balance
export interface AccountBalance {
    total: string;
    stateStaked: string;
    staked: string;
    available: string;
}

**Comment by dinhnhat0401** [comment]
Note 2021/01/05
- Tim hiểu về địa chỉ gửi, nhận near trong sample
- Cách setup ví của platform
-  Chuyển near từ ví của platform sang ví của người dùng đã connect vào hệ thống.
- Lấy balance mới của người dùng và hiển thị.

**Comment by v3kthp** [comment]
- Tạo smartcontract bằng Rust (https://docs.near.org/vi/docs/develop/contracts/rust/intro): Tạo và deploy 1 smart contract vs account của mình lên blocktrain để có thể sử dụng nó trong dapp
- Sử dụng ví của mình như 1 master account khi sign smartcontract (https://docs.near.org/vi/docs/develop/contracts/sandbox)
